"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.eval = exports.evaluate = exports.evaluateAsync = exports.comp = exports.compile = exports.compileProject = exports.compileProjectAsync = exports.compileFile = exports.compileFileAsync = void 0;
const compile_1 = require("./compile");
Object.defineProperty(exports, "compileFileAsync", { enumerable: true, get: function () { return compile_1.compileFileAsync; } });
Object.defineProperty(exports, "compileFile", { enumerable: true, get: function () { return compile_1.compileFile; } });
Object.defineProperty(exports, "compileProjectAsync", { enumerable: true, get: function () { return compile_1.compileProjectAsync; } });
Object.defineProperty(exports, "compileProject", { enumerable: true, get: function () { return compile_1.compileProject; } });
Object.defineProperty(exports, "compile", { enumerable: true, get: function () { return compile_1.compileProject; } });
Object.defineProperty(exports, "comp", { enumerable: true, get: function () { return compile_1.compileProject; } });
const evaluate_1 = require("./evaluate");
Object.defineProperty(exports, "evaluateAsync", { enumerable: true, get: function () { return evaluate_1.evaluateAsync; } });
Object.defineProperty(exports, "evaluate", { enumerable: true, get: function () { return evaluate_1.evaluate; } });
Object.defineProperty(exports, "eval", { enumerable: true, get: function () { return evaluate_1.evaluate; } });
